// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIiErvrLqGKwBe1EuU1hgbMTm714H86IU',
    appId: '1:192078583382:web:e466767dbb4fc3860f4df7',
    messagingSenderId: '192078583382',
    projectId: 'flutter-login-signup-74b8b',
    authDomain: 'flutter-login-signup-74b8b.firebaseapp.com',
    storageBucket: 'flutter-login-signup-74b8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjYpXpza7shnM7WRSIvP_bDd_8vRVB3YY',
    appId: '1:192078583382:android:fea479736274143a0f4df7',
    messagingSenderId: '192078583382',
    projectId: 'flutter-login-signup-74b8b',
    storageBucket: 'flutter-login-signup-74b8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXiJfjcqjz-NUcLPY63RgcDE2_1yv4C0A',
    appId: '1:192078583382:ios:ed885eb55dd699e80f4df7',
    messagingSenderId: '192078583382',
    projectId: 'flutter-login-signup-74b8b',
    storageBucket: 'flutter-login-signup-74b8b.appspot.com',
    iosClientId: '192078583382-t4hnrtnmbcn36hn91pp2t3amiga4unuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXiJfjcqjz-NUcLPY63RgcDE2_1yv4C0A',
    appId: '1:192078583382:ios:ed885eb55dd699e80f4df7',
    messagingSenderId: '192078583382',
    projectId: 'flutter-login-signup-74b8b',
    storageBucket: 'flutter-login-signup-74b8b.appspot.com',
    iosClientId: '192078583382-t4hnrtnmbcn36hn91pp2t3amiga4unuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );
}
